### ISSUE TITLE
Rename Calendar in bot message

### ISSUE THREAD

**Issue by alinago92** [sradyushkin/gcalendar-reminder-bot#1]
![image](https://user-images.githubusercontent.com/94549590/142230314-706dbdba-6b69-4538-bafe-6c3f03bc1664.png)
 I'd love to see human readable calendar name instead of the identificator in bot's notification message. For example, "Крастота" instead of the one on screenshot

**Comment by sradyushkin** [comment]
done https://github.com/sradyushkin/gcalendar-reminder-bot/commit/f68576f7a7714b71ec3b8a52ea13bb94f1bf6cd9
