### ISSUE TITLE
Extra fields about event

### ISSUE THREAD

**Issue by alinago92** [sradyushkin/gcalendar-reminder-bot#2]
I'd love to see some information about the event from calendar, such as: begining and ending time(if it's not for all day), place (if specified), description (if specified)
![image](https://user-images.githubusercontent.com/94549590/142418346-577bfa2e-5e1f-4113-8b12-b7bbf3fcce66.png)

**Comment by sradyushkin** [comment]
done https://github.com/sradyushkin/gcalendar-reminder-bot/commit/39ef883f8065a5793a9736e388a2170651f8d60f
